import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { Button } from "@/components/ui/button";
import { AlertCircle, CheckCircle, Activity, Download } from "lucide-react";

interface DiagnosisReportProps {
  diagnosis: string;
  image: string;
}

export const DiagnosisReport = ({ diagnosis, image }: DiagnosisReportProps) => {
  // Parse diagnosis text to identify severity
  const isHealthy = diagnosis.toLowerCase().includes('healthy') || 
                    diagnosis.toLowerCase().includes('no disease');
  const isSevere = diagnosis.toLowerCase().includes('severe');

  const handleDownload = () => {
    const status = isHealthy ? "Healthy" : isSevere ? "Severe" : "Attention Required";
    const reportContent = `
PLANT DISEASE DETECTION REPORT
================================

Date: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}

STATUS: ${status}

ANALYSIS RESULTS:
${diagnosis}

---
This AI-powered diagnosis is for informational purposes only. 
For critical plant health issues or commercial agriculture, please consult 
with a certified plant pathologist or your local agricultural extension office.

Generated by Plant Disease Detection © 2025
    `.trim();

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `plant-diagnosis-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6 animate-in fade-in-0 slide-in-from-bottom-4 duration-500">
      <div className="text-center space-y-4">
        <div>
          <h2 className="text-3xl font-bold mb-2 bg-gradient-primary bg-clip-text text-transparent">
            Diagnosis Report
          </h2>
          <p className="text-muted-foreground">
            AI-powered plant health analysis
          </p>
        </div>
        <Button
          onClick={handleDownload}
          variant="outline"
          className="gap-2"
        >
          <Download className="h-4 w-4" />
          Download Report
        </Button>
      </div>

      <div className="grid md:grid-cols-2 gap-6">
        <Card className="p-0 overflow-hidden shadow-soft">
          <img
            src={image}
            alt="Analyzed plant"
            className="w-full h-full object-cover"
          />
        </Card>

        <Card className="p-6 space-y-4 shadow-soft">
          <div className="flex items-center gap-3">
            {isHealthy ? (
              <>
                <div className="rounded-full bg-success/10 p-2">
                  <CheckCircle className="h-6 w-6 text-success" />
                </div>
                <div>
                  <h3 className="font-semibold text-lg">Plant Status</h3>
                  <Badge variant="outline" className="border-success text-success">
                    Healthy
                  </Badge>
                </div>
              </>
            ) : (
              <>
                <div className="rounded-full bg-warning/10 p-2">
                  <AlertCircle className="h-6 w-6 text-warning" />
                </div>
                <div>
                  <h3 className="font-semibold text-lg">Disease Detected</h3>
                  <Badge variant="outline" className={isSevere ? "border-destructive text-destructive" : "border-warning text-warning"}>
                    {isSevere ? "Severe" : "Attention Required"}
                  </Badge>
                </div>
              </>
            )}
          </div>

          <Separator />

          <div className="space-y-3">
            <div className="flex items-start gap-2">
              <Activity className="h-5 w-5 text-primary mt-0.5 flex-shrink-0" />
              <div className="flex-1">
                <h4 className="font-semibold mb-1">Analysis Results</h4>
                <p className="text-sm text-muted-foreground whitespace-pre-wrap">
                  {diagnosis}
                </p>
              </div>
            </div>
          </div>
        </Card>
      </div>

      <Card className="p-6 bg-secondary/50 border-primary/20 shadow-soft">
        <h4 className="font-semibold mb-3 flex items-center gap-2">
          <AlertCircle className="h-5 w-5 text-primary" />
          Important Note
        </h4>
        <p className="text-sm text-muted-foreground">
          This AI-powered diagnosis is for informational purposes only. For critical plant health 
          issues or commercial agriculture, please consult with a certified plant pathologist or 
          your local agricultural extension office for professional advice.
        </p>
      </Card>
    </div>
  );
};
